SEED_RACES = [
    {
        "slug": "seoul-river-night-run-2026",
        "title": "서울 리버 나이트 런 2026",
        "region": "서울",
        "venue": "여의도 한강공원 이벤트광장",
        "event_date": "2026-06-20",
        "registration_status": "registration_open",
        "distances": ["10km", "5km"],
        "thumbnail_url": "https://images.unsplash.com/photo-1486218119243-13883505764c",
        "is_bookmarked": True,
        "start_time": "18:30",
        "registration_open_at": "2026-03-15",
        "registration_close_at": "2026-06-10",
        "event_status": "upcoming",
        "official_url": None,
        "apply_url": None,
        "contact_email": None,
        "contact_phone": "02-1234-5678",
        "description": "도심 야경과 함께 달리는 한강 야간 러닝 이벤트입니다.",
        "source_url": None,
        "last_checked_at": "2026-05-05",
    },
    {
        "slug": "busan-ocean-half-marathon-2026",
        "title": "부산 오션 하프 마라톤 2026",
        "region": "경상",
        "venue": "광안리 해변공원",
        "event_date": "2026-09-13",
        "registration_status": "registration_upcoming",
        "distances": ["Half", "10km"],
        "thumbnail_url": "https://images.unsplash.com/photo-1552674605-db6ffd4facb5",
        "is_bookmarked": False,
        "start_time": "08:00",
        "registration_open_at": "2026-06-01",
        "registration_close_at": "2026-08-31",
        "event_status": "upcoming",
        "official_url": None,
        "apply_url": None,
        "contact_email": None,
        "contact_phone": "051-555-7777",
        "description": "광안대교와 바다 풍경을 따라 달리는 대표 하프 마라톤입니다.",
        "source_url": None,
        "last_checked_at": "2026-05-05",
    },
    {
        "slug": "jeju-trail-festival-2026",
        "title": "제주 트레일 러닝 페스티벌 2026",
        "region": "제주",
        "venue": "제주 사려니숲길",
        "event_date": "2026-10-03",
        "registration_status": "registration_open",
        "distances": ["21km", "10km"],
        "thumbnail_url": "https://images.unsplash.com/photo-1461896836934-ffe607ba8211",
        "is_bookmarked": True,
        "start_time": "07:30",
        "registration_open_at": "2026-04-10",
        "registration_close_at": "2026-09-15",
        "event_status": "upcoming",
        "official_url": None,
        "apply_url": None,
        "contact_email": None,
        "contact_phone": "064-222-3333",
        "description": "숲길과 오름 풍경을 함께 즐기는 트레일 러닝 행사입니다.",
        "source_url": None,
        "last_checked_at": "2026-05-05",
    },
]
